{ stdenv, nixpkgs, backend, nextpnr, python3, coreutils, findutils
, gnused, gnugrep, ... }:

stdenv.mkDerivation rec {
  pname = "nextpnr-chipdb";
  version = nextpnr.version;
  inherit backend;

  # The himbaechel chipdb is generated by the in-tree gen/xilinx_gen.py from
  # the nextpnr source, against the same prjxray-db checkout nextpnr.nix was
  # configured with.  Take both from the nextpnr package (exposed via its
  # passthru) rather than re-fetching them here, so the chipdb can never be
  # built from a source or db that drifted from the packaged nextpnr.
  nextpnr-src = nextpnr.src;
  prjxray-db = nextpnr.prjxray-db;

  # No source of our own to unpack: everything this derivation needs comes
  # from the nextpnr package (bbasm, the generator, the prjxray-db checkout).
  dontUnpack = true;

  buildInputs = [ nextpnr python3 coreutils findutils gnused gnugrep ];
  buildPhase = ''
    mkdir -p $out
    find ${prjxray-db}/ -type d -name "*-*" -mindepth 1 -maxdepth 2 |\
      sed -e 's,.*/\(.*\)-.*$,\1,g' -e 's,\./,,g' |\
      sort |\
      uniq >\
    $out/footprints.txt

    touch $out/built-footprints.txt

    for i in `cat $out/footprints.txt`
    do
        if   [[ $i = xc7a* ]]; then ARCH=artix7
        elif [[ $i = xc7k* ]]; then ARCH=kintex7
        elif [[ $i = xc7s* ]]; then ARCH=spartan7
        elif [[ $i = xc7v* ]]; then ARCH=virtex7
        elif [[ $i = xc7z* ]]; then ARCH=zynq7
        else
          echo "unsupported architecture for footprint $i"
          exit 1
        fi

        if [[ $ARCH != "${backend}" ]]; then
          continue
        fi

        # The generator takes a die name (the leading device token of the
        # part), while the chipdb file is named for the footprint: that is
        # what demo-projects/regression/run.sh and the demos resolve.  The
        # a35t die directory does not exist in prjxray-db -- its part
        # directories alias the a50t die -- so map xc7a35t* to xc7a50t.
        DIE=`echo $i | sed -E 's/^(xc7(s[0-9]+t?|a[0-9]+t|k[0-9]+t|z[0-9]+t?|v[xh]?[0-9]+t)).*/\1/'`
        if [[ $DIE = xc7a35t ]]; then
          DIE=xc7a50t
        fi

        # prjxray-db sometimes carries package dirs whose die directory has
        # not landed yet (xc7z035*): the die is simply absent, and the
        # generator then fails and takes the whole family package (and with
        # it every consumer of the chipdb) down.  Skip footprints whose die
        # tilegrid.json is missing; they become buildable once the die lands
        # upstream.
        if [ ! -f "${prjxray-db}/$ARCH/$DIE/tilegrid.json" ]; then
          echo "skipping $i (no $DIE die tilegrid.json in prjxray-db)"
          continue
        fi

        python3 ${nextpnr-src}/himbaechel/uarch/xilinx/gen/xilinx_gen.py \
          --xray ${prjxray-db}/$ARCH \
          --device $DIE \
          --bba $i.bba 2>&1
        bbasm -l $i.bba $out/$i.bin
        # The .bba intermediates are tens of GB; keep peak disk usage at a
        # single footprint.
        rm -f $i.bba
        echo $i >> $out/built-footprints.txt
    done

    mv -f $out/built-footprints.txt $out/footprints.txt

    # make the chipdb directory available
    mkdir -p $out/bin
    cat > $out/bin/get_chipdb_${backend}.sh <<EOF
    #!${nixpkgs.runtimeShell}
    echo -n $out
    EOF
    chmod 755 $out/bin/get_chipdb_${backend}.sh
  '';

  dontInstall = true;
}
