{
  description = "Open RTL synthesis framework and tools";
  nixConfig.bash-prompt = "[nix(openXC7)] ";

  # Nixpkgs / NixOS version to use.
  inputs.nixpkgs.url = "nixpkgs/nixos-unstable";
  inputs.flake-utils.url = "github:numtide/flake-utils";
  outputs = { self, nixpkgs, flake-utils, ... }:
    let

      # to work with older version of flakes
      lastModifiedDate =
        self.lastModifiedDate or self.lastModified or "19700101";

      # Generate a user-friendly version number.
      version = builtins.substring 0 8 lastModifiedDate;

      # System types to support.
      supportedSystems =
        [ "x86_64-linux" "x86_64-darwin" "aarch64-linux" "aarch64-darwin" ];

      # Helper function to generate an attrset '{ x86_64-linux = f "x86_64-linux"; ... }'.
      forAllSystems = nixpkgs.lib.genAttrs supportedSystems;

      # Nixpkgs instantiated for supported system types.
      nixpkgsFor = forAllSystems (system: import nixpkgs { inherit system; });
    in {
      # Provide some binary packages for selected system types.
      packages = forAllSystems (system:
        let
          pkgs = nixpkgsFor.${system};
          inherit (pkgs) lib callPackage stdenv fetchgit fetchFromGitHub;
        in rec {
          # The himbaechel Xilinx uarch: the successor of nextpnr-xilinx,
          # developed in openXC7's fork of upstream nextpnr.
          nextpnr = callPackage ./nix/nextpnr.nix { };

          # Consumer-facing name: openXC7's demos, its regression harness and
          # xc7-bitstream-tools all invoke bin/nextpnr-xilinx with the fork's
          # flags; the new package installs a shim of that name which
          # translates them, so point the name at it (this is the switch).
          nextpnr-xilinx = nextpnr;

          # The legacy nextpnr-xilinx fork, kept buildable for comparison.
          nextpnr-xilinx-legacy = callPackage ./nix/nextpnr-xilinx.nix { };

          prjxray = callPackage ./nix/prjxray.nix { };

          fasm = with pkgs;
            with python312Packages;
            callPackage ./nix/fasm {
              # NOTE(jleightcap): calling this package here is clucky.
              # contorted structure here to make the `nix/fasm` directory be
              # drop-in to upstream python-modules in nixpkgs.
              inherit buildPythonPackage pythonOlder textx cython fetchpatch jre_headless antlr4_9;
            };

          nextpnr-chipdb = {
            artix7 = callPackage ./nix/nextpnr-chipdb.nix {
              backend = "artix7";
              nixpkgs = pkgs;
              inherit nextpnr;
            };
            kintex7 = callPackage ./nix/nextpnr-chipdb.nix {
              backend = "kintex7";
              nixpkgs = pkgs;
              inherit nextpnr;
            };
            spartan7 = callPackage ./nix/nextpnr-chipdb.nix {
              backend = "spartan7";
              nixpkgs = pkgs;
              inherit nextpnr;
            };
            virtex7 = callPackage ./nix/nextpnr-chipdb.nix {
              backend = "virtex7";
              nixpkgs = pkgs;
              inherit nextpnr;
            };
            zynq7 = callPackage ./nix/nextpnr-chipdb.nix {
              backend = "zynq7";
              nixpkgs = pkgs;
              inherit nextpnr;
            };
          };

          # The consumer-facing name: openXC7's demo-projects workflows pin
          # `.#nextpnr-xilinx-chipdb.<family>` (smoke.yml, heavy.yml), so this
          # is the switch for them too -- they now get the chipdbs generated by
          # the himbaechel flow from the same prjxray-db revision.
          nextpnr-xilinx-chipdb = nextpnr-chipdb;

          nextpnr-xilinx-legacy-chipdb = {
            artix7 = callPackage ./nix/nextpnr-xilinx-chipdb.nix {
              backend = "artix7";
              nixpkgs = pkgs;
              nextpnr-xilinx = nextpnr-xilinx-legacy;
              inherit prjxray;
            };
            kintex7 = callPackage ./nix/nextpnr-xilinx-chipdb.nix {
              backend = "kintex7";
              nixpkgs = pkgs;
              nextpnr-xilinx = nextpnr-xilinx-legacy;
              inherit prjxray;
            };
            spartan7 = callPackage ./nix/nextpnr-xilinx-chipdb.nix {
              backend = "spartan7";
              nixpkgs = pkgs;
              nextpnr-xilinx = nextpnr-xilinx-legacy;
              inherit prjxray;
            };
            virtex7 = callPackage ./nix/nextpnr-xilinx-chipdb.nix {
              backend = "virtex7";
              nixpkgs = pkgs;
              nextpnr-xilinx = nextpnr-xilinx-legacy;
              inherit prjxray;
            };
            zynq7 = callPackage ./nix/nextpnr-xilinx-chipdb.nix {
              backend = "zynq7";
              nixpkgs = pkgs;
              nextpnr-xilinx = nextpnr-xilinx-legacy;
              inherit prjxray;
            };
          };

          fpga-assembler = (builtins.getFlake "github:lromor/fpga-assembler/6ff89a2d53edc9d74a402c28096450473b67de13").packages.${system}.default;

          sv-elab = callPackage ./nix/sv-elab.nix { };
        });

      # contains a mutually consistent set of packages for a full toolchain using nextpnr-xilinx.
      devShell = forAllSystems (system:
        nixpkgsFor.${system}.mkShell {
          buildInputs = (with self.packages.${system}; [
            fasm
            fpga-assembler
            nextpnr-xilinx
            prjxray
            sv-elab
          ]) ++ (with nixpkgsFor.${system}; [
            yosys
            ghdl
            yosys-ghdl
            openfpgaloader
            python312Packages.pyyaml
            python312Packages.textx
            python312Packages.simplejson
            python312Packages.intervaltree
          ]);

          shellHook =
            let mypkgs  = self.packages.${system};
                nixpkgs = nixpkgsFor.${system};
                pyPkgPath = "/lib/python3.12/site-packages/:";
            in nixpkgs.lib.concatStrings [
              "export YOSYS_PLUGIN_PATH=" mypkgs.sv-elab.outPath "\n"
              "export NEXTPNR_XILINX_DIR=" mypkgs.nextpnr-xilinx.outPath "\n"
              # The himbaechel flow has no bbaexport.py (its chipdbs come from
              # nextpnr-chipdb.<family>), so NEXTPNR_XILINX_PYTHON_DIR is gone.
              # PRJXRAY_DB_DIR now points at the prjxray-db checkout the
              # nextpnr package was built against; fasm2frames still reads it.
              "export PRJXRAY_DB_DIR=" mypkgs.nextpnr.prjxray-db.outPath "\n"
              "export PRJXRAY_PYTHON_DIR=" mypkgs.prjxray.outPath "/usr/share/python3/\n"
              ''export PYTHONPATH=''$PYTHONPATH:''$PRJXRAY_PYTHON_DIR:'' 
                mypkgs.fasm.outPath pyPkgPath
                nixpkgs.python312Packages.textx.outPath pyPkgPath
                nixpkgs.python312Packages.arpeggio.outPath pyPkgPath
                nixpkgs.python312Packages.pyyaml.outPath pyPkgPath
                nixpkgs.python312Packages.simplejson.outPath pyPkgPath
                nixpkgs.python312Packages.intervaltree.outPath pyPkgPath
                nixpkgs.python312Packages.sortedcontainers.outPath pyPkgPath

                # Needed by fasm to import antlr correctly
                nixpkgs.python312Packages.cython.outPath pyPkgPath
                nixpkgs.python312Packages.distutils.outPath pyPkgPath
                nixpkgs.python312Packages.jaraco-envs.outPath pyPkgPath
                nixpkgs.python312Packages.jaraco-functools.outPath pyPkgPath
                nixpkgs.python312Packages.more-itertools.outPath pyPkgPath
                nixpkgs.python312Packages.packaging.outPath pyPkgPath
                "\n"
            ];
        }
      );

      # Minimal shell with the build dependencies of nextpnr-xilinx,
      # used by CI (and developers) to build and run its unit tests.
      ci-tests = forAllSystems (system:
        nixpkgsFor.${system}.mkShell {
          buildInputs = with nixpkgsFor.${system}; [
            cmake
            pkg-config
            python3
            python3Packages.boost
            eigen
          ];
        });

      dockerImage = forAllSystems (system:
        let
          pkgs = nixpkgsFor.${system};
          mypkgs = self.packages.${system};
          chipdb = mypkgs.nextpnr-chipdb;
          pyPkgPath = "/lib/python3.10/site-packages/:";
        in
        pkgs.dockerTools.buildImage {
          name = "openxc7-docker";
          copyToRoot = pkgs.buildEnv {
            name = "image-root";
            paths = self.devShell.${system}.buildInputs ++ (with pkgs; [
              bashInteractive
              findutils
              gnused
              gnugrep
              coreutils
              gnumake
              python312
            ]) ++ (with chipdb; [
              spartan7
              artix7
              kintex7
              zynq7
            ]);
            pathsToLink = [ "/bin" ] ++ (with pkgs.dockerTools; [
              usrBinEnv
              binSh
            ]);
          };

          runAsRoot = pkgs.lib.concatStrings [ ''
            #!${pkgs.runtimeShell}
            mkdir -p /work
            cat > /bin/devshell <<EOF
            #!${pkgs.runtimeShell}
            '' self.devShell.${system}.shellHook "\n"
            "export PRJXRAY_DB_DIR=" mypkgs.nextpnr.prjxray-db.outPath "\n"
            "export PRJXRAY_PYTHON_DIR=" mypkgs.prjxray.outPath "/usr/share/python3/\n"
            "export LOCALE_ARCHIVE=/usr/lib/locale/locale-archive"
            ''export PYTHONPATH=\''$PYTHONPATH:\''$PRJXRAY_PYTHON_DIR:''
              pkgs.python312Packages.textx.outPath pyPkgPath
              pkgs.python312Packages.pyyaml.outPath pyPkgPath
              pkgs.python312Packages.simplejson.outPath pyPkgPath
              pkgs.python312Packages.intervaltree.outPath pyPkgPath
              pkgs.python312Packages.arpeggio.outPath pyPkgPath
              pkgs.python312Packages.setuptools.outPath pyPkgPath
              pkgs.python312Packages.future.outPath pyPkgPath
              pkgs.python312Packages.sortedcontainers.outPath pyPkgPath
              mypkgs.fasm.outPath "/lib/python3.12/site-packages/"
              "\n"
            "export NEXTPNR_XILINX_DIR=" mypkgs.nextpnr-xilinx.outPath "\n"
            "export SPARTAN7_CHIPDB="    chipdb.spartan7.outPath "\n"
            "export ARTIX7_CHIPDB="      chipdb.artix7.outPath "\n"
            "export KINTEX7_CHIPDB="     chipdb.kintex7.outPath "\n"
            "export ZYNQ7_CHIPDB="       chipdb.zynq7.outPath "\n"
            "\nexec ${pkgs.bashInteractive}/bin/bash\n"
            ''EOF
            chmod 755 /bin/devshell
          ''];

          config = {
            Cmd = [ "/bin/devshell" ];
            WorkingDir = "/work";
            Volumes = { "/work" = { }; };
          };
        }
      );
    };
}
